services:
    freemitbbs.hotforums.listener:
        class: freemitbbs\hotforums\event\listener
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@?phpbb.collapsiblecategories.operator'
        tags:
            - { name: event.listener }
