services:
    freemitbbs.disposableemailblocker.domain_blocklist:
        class: freemitbbs\disposableemailblocker\service\domain_blocklist
        arguments:
            - '%core.root_path%'

    freemitbbs.disposableemailblocker.listener:
        class: freemitbbs\disposableemailblocker\event\listener
        arguments:
            - '@freemitbbs.disposableemailblocker.domain_blocklist'
            - '@language'
            - '@user'
        tags:
            - { name: event.listener }

    freemitbbs.disposableemailblocker.cron.refresh_domains:
        class: freemitbbs\disposableemailblocker\cron\refresh_domains
        arguments:
            - '@config'
            - '@freemitbbs.disposableemailblocker.domain_blocklist'
        calls:
            - [set_name, [cron.task.freemitbbs.disposableemailblocker.refresh_domains]]
        tags:
            - { name: cron.task }
